version: "3"
services:
    web:
        build: .
        image: php_apache_img
        container_name: php_apache_container
        ports:
            - "80:80"
        volumes:
            - ./php:/var/www/html/
        depends_on:
            - db
    db:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        volumes:
            - db_mysql_vol:/var/lib/mysql
        environment:
            MYSQL_DATABASE: todolist
            MYSQL_ROOT_PASSWORD: root

    control:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            MYSQL_ROOT_PASSWORD: root

volumes:
    db_mysql_vol:
